version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL="postgresql://myuser:mypassword@localhost:5432/aliexpress-db??schema=public"
  #     - SUPABASE_URL=https://jqmchpvijyohpdincoom.supabase.co
  #     - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbWNocHZpanlvaHBkaW5jb29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMzNzIxOTUsImV4cCI6MjAzODk0ODE5NX0.eU6pi3Cydw8hAi_-oJp8WHCYnYtfZuHjFSLfpNfFtDA
  #     - STRIPE_PK_KEY=pk_test_omlXjzDjv5JiiZriL2q7XT3d00PisYvFQu
  #     - STRIPE_SK_KEY=sk_test_OdhcxJOodiL864hUbQXsmXWO002jY45IkF

  db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=aliexpress-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
